var annotated_dup =
[
    [ "Aircraft", "class_aircraft.html", "class_aircraft" ],
    [ "AircraftMover", "struct_aircraft_mover.html", null ],
    [ "Command", "struct_command.html", null ],
    [ "CommandQueue", "class_command_queue.html", "class_command_queue" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "FrameResource", "struct_frame_resource.html", null ],
    [ "Game", "class_game.html", null ],
    [ "GameState", "class_game_state.html", "class_game_state" ],
    [ "MaterialData", "struct_material_data.html", null ],
    [ "MenuState", "class_menu_state.html", "class_menu_state" ],
    [ "ObjectConstants", "struct_object_constants.html", null ],
    [ "PassConstants", "struct_pass_constants.html", null ],
    [ "PauseState", "class_pause_state.html", "class_pause_state" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "RenderItem", "struct_render_item.html", null ],
    [ "SceneNode", "class_scene_node.html", "class_scene_node" ],
    [ "SpriteNode", "class_sprite_node.html", "class_sprite_node" ],
    [ "State", "class_state.html", "class_state" ],
    [ "StateStack", "class_state_stack.html", "class_state_stack" ],
    [ "TitleState", "class_title_state.html", "class_title_state" ],
    [ "Vertex", "struct_vertex.html", null ],
    [ "Waves", "class_waves.html", null ],
    [ "World", "class_world.html", "class_world" ]
];